### PR TITLE
Issue #133: Exclude binaries for other platforms during build

### LINKED ISSUE #133: Bundle only necessary binaries when building
Exclude binaries from other OS when building with electron-builder.

### PR DESCRIPTION
**Pull request by willvincent**
Fix #133

### CODE REVIEW

**Comment by willvincent** [comment]
Need to see if the tests pass, only the osx build works for me locally. 

But... this should exclude all of the bundled php files for linux (didn't look like there was a linux specific binary), exclude the .exe and .dll for mac, and exclude the osx file for windows builds.

**Comment by rafajaques** [comment]
To test locally you may run `npm run test`.

**Comment by willvincent** [comment]
`npm run test` does not run the various platform builds. It just runs the linter, which is fine. The travis and appveyor CI servers _do_ appear to run platform builds, and it looks like each worked as expected if you inspect their output:

Appveyor:
```
npm run publish:win32
> @ publish:win32 C:\projects\php-assistant
> build --windows --ia32 --publish onTagOrDraft
CI detected, publish is set to onTagOrDraft, but neither GH_TOKEN nor BT_TOKEN is not set, so artifacts will be not published
Rebuilding app dependencies for arch ia32 to C:\projects\php-assistant\app
Packaging for platform win32 ia32 using electron 1.4.3 to dist\win-ia32-unpacked
Warning: For windows consider only distributing 64-bit, see https://github.com/electron-userland/electron-builder/issues/359#issuecomment-214851130
Building squirrel ia32 installer
Build success
```

Travis:
```
 npm run publish:$TRAVIS_OS_NAME
> @ publish:osx /Users/travis/build/rafajaques/php-assistant
> build --osx --publish onTagOrDraft
CI detected, publish is set to onTagOrDraft, but neither GH_TOKEN nor BT_TOKEN is not set, so artifacts will be not published
Rebuilding app dependencies for arch x64 to /Users/travis/build/rafajaques/php-assistant/app
Packaging for platform darwin x64 using electron 1.4.3 to dist/mac
Warning: App is not signed: CSC_LINK is not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Must be "Developer ID Application:" or custom non-Apple code signing certificate
Creating DMG
Creating MacOS zip
```
```
npm run publish:$TRAVIS_OS_NAME
> @ publish:linux /home/travis/build/rafajaques/php-assistant
> build --linux deb rpm freebsd pacman tar.xz --publish onTagOrDraft
CI detected, publish is set to onTagOrDraft, but neither GH_TOKEN nor BT_TOKEN is not set, so artifacts will be not published
Rebuilding app dependencies for arch x64 to /home/travis/build/rafajaques/php-assistant/app
Packaging for platform linux x64 using electron 1.4.3 to dist/linux-unpacked
```

**Comment by rafajaques** [comment]
Oh right. I thought you were talking about linter.
Never mind. The builds are ok.
Thanks.

**Comment by willvincent** [comment]
I suspect those builds will _never_ work properly on my machine since it's not windows and not linux.  I can build mac just fine locally, but that's it.  I did verify the build omitted the windows binaries though. 

screen shot 2016-10-28 at 10 42 22 am

**Pull request merged**
