### PR TITLE
Issue #173: Enable transparent window if Aeroglass is available

### LINKED ISSUE #173: Enable Aeroglass if available
Test Aeroglass in Windows. If possible, enable it.

Maybe the best time to do that is when creating the main window: [main.js#78](https://github.com/rafajaques/php-assistant/blob/master/app/main.js#L78).

Reference: http://electron.atom.io/docs/api/system-preferences/#systempreferencesisaeroglassenabled-windows

### PR DESCRIPTION
**Pull request by willvincent**
Fixes #173

### CODE REVIEW

**Comment by willvincent** [comment]
Please add hacktoberfest label

:smile:

**Comment by rafajaques** [comment]
Very good! Thank you very much.
Unfortunately I don't have Windows to test.
May you send a screenshot?

**Comment by willvincent** [comment]
I don't have windows either, but the logic is correct.

**Comment by rafajaques** [comment]
No problem. I'll try soon!
Thanks! :)

**Comment by rafajaques** [comment]
And don't worry about hacktoberfest. Every PR counts, even if there is no label.

**Comment by willvincent** [comment]
Yea, figured that out when I re-read the hacktoberfest info last night :smile:

**Pull request merged**
