### PR TITLE
Add some global variables to ESlint config

### PR DESCRIPTION
**Pull request by Johann-S**
To fix some problem with ESlint, we have to declare global vars

### CODE REVIEW

**Comment by Johann-S** [comment]
@rafajaques with this PR, ESlint is fully configurated. So we will have to fix the current code of PHP Assistant

And it would be great to enable Travis because it will check all PR for us

**Comment by rafajaques** [comment]
OK! I'll look forward to enable Travis.

**Comment by rafajaques** [comment]
Travis enabled in repository.

**Comment by Johann-S** [comment]
Yes but we have to create ``.travis.yml`` file

**Pull request merged**
