### PR TITLE
Update Indonesian Language

### PR DESCRIPTION
**Pull request by hndr91**
Notes :
Need an improvement especially for term
1. Toggle Mode
2. Notification Bar
3. Tray Application

Everything is done, but I think I still cannot find perfect term for 3 term above in Indonesian, so I keep it as english term. I keep the orginal application name too

### CODE REVIEW

**Comment by rafajaques** [comment]
Very good! Thanks!

Maybe you can think on these terms like that:

1. Toggle Mode = Switch Mode or Switch Between Modes or even Change Mode
2. Notification Bar = That's the tray or notification area of the OS, usually the icons near the clock.
3. Tray Application = An application that goes as an icon in the tray/notification.

**Comment by hndr91** [comment]
Something english term doesn't have perfect match in Indonesian term, i mean in the true meaning of the term, we have suitable word in indonesian, but sometimes not the true meaning of it, so we keep it as the originital term to keep original meaning. So for now,  I will find the best way based on your description, ty @rafajaques

**Comment by rafajaques** [comment]
I will merge the pull request. You can sync your repo and then send a new PR.
Thanks!

**Comment by hndr91** [comment]
thx @rafajaques i will make a new PR if I found the best term

**Pull request merged**
